### PR TITLE
Use a consistent string with other samples

### PR DESCRIPTION
**Pull request by mattmoor**
cc @jamesward

### CODE REVIEW

**Comment by mattmoor** [comment]
cc @coryan

**Comment by jamesward** [comment]
Your attention to detail is heroic.

**Comment by mattmoor** [comment]
I'm kinda cheating.  I have tests 😉 

https://github.com/mattmoor/mink/blob/6d1c74359127844ccd058bc1f499625de5efc4bf/.github/workflows/minkind-cli.yaml#L339

**Comment by jamesward** [comment]
Automated tests are the best form of heroism.

**Pull request merged**
