### PR TITLE
Remove experimental env var flag from Ruby samples.

### PR DESCRIPTION
**Pull request by asriniva**

### CODE REVIEW

**Comment by jamesward** [comment]
It appears this change doesn't work yet:
```
Error: attempted to build and failed: pack build failed: exit status 1, output:
=== Ruby - missing entrypoint (google.ruby.missing-entrypoint@0.0.1) ===
Failure: (ID: 052f1e5c) Failed to run /bin/build: for Ruby, an entrypoint must be manually set, either with "GOOGLE_ENTRYPOINT" env var or by creating a "Procfile" file
--------------------------------------------------------------------------------
Sorry your project couldn't be built.
Our documentation explains ways to configure Buildpacks to better recognise your project:
 -> https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md
If you think you've found an issue, please report it:
 -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
--------------------------------------------------------------------------------
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

**Comment by asriniva** [comment]
Should work now, image has been rebuilt off of https://github.com/GoogleCloudPlatform/buildpacks/commit/e345647e8a946d89e6deb5c0d2ce81d0831ef133.

**Comment by jamesward** [comment]
Cool, it built! Now getting an error on run:
```
<internal:/layers/google.ruby.runtime/ruby/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sinatra (LoadError)
```

BTW, You can test your change by clicking the deploy button on your fork.

**Comment by asriniva** [comment]
Made some changes. Wasn't able to get the one currently in master branch working (without this PR), but made some changes to the sample app to get it working. The deploy button on the fork still pulls from the master branch looks like, so I had to change the cloudshell command slightly.

**Comment by jamesward** [comment]
Note: If you are viewing your branch on GitHub when you click the button, it should checkout the branch.

**Pull request merged**
